import type { HeroTag } from "./types.ts";

/** Internal short names (npc_dota_hero_* without prefix). */
export const HERO_TAGS: Record<string, HeroTag[]> = {
  ancient_apparition: ["magic", "stun"],
  antimage: ["physical", "passive"],
  arc_warden: ["physical", "illusion"],
  axe: ["stun", "physical", "passive"],
  bane: ["stun", "silence", "magic"],
  batrider: ["stun", "magic"],
  beastmaster: ["stun"],
  bloodseeker: ["physical"],
  bounty_hunter: ["invis", "physical"],
  brewmaster: ["evasion", "stun", "physical", "passive"],
  bristleback: ["physical", "passive"],
  broodmother: ["physical", "invis"],
  centaur: ["stun", "physical"],
  chaos_knight: ["illusion", "stun", "physical"],
  chen: ["heal"],
  clinkz: ["invis", "physical"],
  clockwerk: ["stun"],
  crystal_maiden: ["magic", "stun"],
  dark_seer: ["illusion"],
  dark_willow: ["stun", "silence", "magic"],
  dawnbreaker: ["physical", "stun", "heal"],
  dazzle: ["heal", "magic"],
  death_prophet: ["magic", "silence"],
  disruptor: ["silence", "magic", "stun"],
  doom_bringer: ["silence", "magic"],
  dragon_knight: ["stun", "physical"],
  drow_ranger: ["physical", "silence"],
  earth_spirit: ["stun"],
  earthshaker: ["stun"],
  elder_titan: ["stun", "magic"],
  ember_spirit: ["physical", "magic"],
  enchantress: ["heal", "magic", "passive"],
  enigma: ["stun", "magic"],
  faceless_void: ["stun", "physical"],
  grimstroke: ["silence", "magic"],
  gyrocopter: ["physical", "stun"],
  hoodwink: ["stun", "physical"],
  huskar: ["physical", "heal", "passive"],
  invoker: ["magic", "stun", "invis"],
  jakiro: ["magic", "stun"],
  juggernaut: ["physical", "heal"],
  keeper_of_the_light: ["magic"],
  kez: ["physical"],
  kunkka: ["stun", "physical"],
  legion_commander: ["stun", "physical"],
  leshrac: ["magic", "stun"],
  lich: ["magic"],
  lifestealer: ["physical"],
  lina: ["magic", "stun"],
  lion: ["stun", "magic"],
  lone_druid: ["physical"],
  luna: ["physical", "magic"],
  lycan: ["physical"],
  magnataur: ["stun", "physical"],
  marci: ["physical", "stun"],
  mars: ["stun", "physical"],
  medusa: ["physical", "magic", "passive"],
  meepo: ["physical", "stun"],
  mirana: ["invis", "stun", "physical"],
  monkey_king: ["physical", "stun"],
  morphling: ["physical", "illusion"],
  muerta: ["physical", "magic"],
  naga_siren: ["illusion", "invis", "stun"],
  necrolyte: ["magic", "heal", "passive"],
  nevermore: ["magic", "physical"],
  night_stalker: ["invis", "silence", "physical"],
  nyx_assassin: ["invis", "stun", "magic"],
  ogre_magi: ["stun", "magic"],
  omniknight: ["heal"],
  oracle: ["heal", "magic"],
  obsidiandestroyer: ["magic", "silence"],
  pangolier: ["physical", "stun"],
  phantom_assassin: ["physical", "evasion", "passive"],
  phantom_lancer: ["illusion", "physical"],
  phoenix: ["magic"],
  primal_beast: ["stun", "physical"],
  puck: ["magic", "silence", "stun"],
  pudge: ["stun"],
  pugna: ["magic", "heal"],
  queenofpain: ["magic", "stun"],
  rattletrap: ["stun"],
  razor: ["physical"],
  riki: ["invis", "physical"],
  ringmaster: ["stun", "silence"],
  rubick: ["magic", "stun"],
  sand_king: ["invis", "stun", "magic"],
  shadow_demon: ["illusion", "magic"],
  shadow_shaman: ["stun", "magic"],
  shredder: ["physical", "magic", "passive"],
  silencer: ["silence", "magic"],
  skeleton_king: ["physical", "stun", "heal", "passive"],
  skywrath_mage: ["magic", "silence"],
  slardar: ["stun", "physical"],
  slark: ["invis", "physical", "passive"],
  snapfire: ["magic", "stun"],
  sniper: ["physical"],
  spectre: ["illusion", "physical", "passive"],
  spirit_breaker: ["stun", "physical"],
  storm_spirit: ["magic", "stun"],
  sven: ["stun", "physical"],
  techies: ["magic", "invis"],
  templar_assassin: ["invis", "physical"],
  terrorblade: ["illusion", "physical"],
  tidehunter: ["stun", "passive"],
  tinker: ["magic"],
  tiny: ["stun", "physical"],
  treant: ["invis", "heal", "stun"],
  troll_warlord: ["physical", "evasion"],
  tusk: ["stun", "physical"],
  undying: ["heal", "magic"],
  ursa: ["physical", "passive"],
  vengefulspirit: ["stun", "physical"],
  venomancer: ["magic"],
  viper: ["magic", "physical", "passive"],
  visage: ["magic"],
  void_spirit: ["magic", "stun"],
  warlock: ["magic", "stun", "heal"],
  weaver: ["invis", "physical"],
  windrunner: ["physical", "stun", "evasion"],
  winter_wyvern: ["magic", "stun", "heal"],
  witch_doctor: ["magic", "stun", "heal"],
  zuus: ["magic", "stun"],
  abaddon: ["heal", "physical", "passive"],
  abyssal_underlord: ["magic"],
  alchemist: ["physical", "stun"],
};

export const SITUATIONAL_ITEMS: {
  tags: HeroTag[];
  items: string[];
  reason: string;
}[] = [
  {
    tags: ["stun", "silence"],
    items: ["black_king_bar", "lotus_orb", "sphere", "aeon_disk", "manta"],
    reason: "vs heavy disable",
  },
  {
    tags: ["magic"],
    items: [
      "pipe",
      "eternal_shroud",
      "mage_slayer",
      "black_king_bar",
      "hood_of_defiance",
      "cloak",
      "glimmer_cape",
      "pipe_of_insight",
    ],
    reason: "vs magic damage",
  },
  {
    tags: ["invis"],
    items: ["dust", "ward_sentry", "gem", "sheepstick", "scepter"],
    reason: "vs invisibility",
  },
  {
    tags: ["evasion"],
    items: ["monkey_king_bar"],
    reason: "vs evasion",
  },
  {
    tags: ["illusion"],
    items: ["bfury", "maelstrom", "mjollnir", "radiance", "crimson_guard", "shivas_guard"],
    reason: "vs illusions",
  },
  {
    tags: ["physical"],
    items: [
      "assault",
      "crimson_guard",
      "heavens_halberd",
      "ghost",
      "blade_mail",
      "shivas_guard",
      "solar_crest",
    ],
    reason: "vs physical cores",
  },
  {
    tags: ["heal"],
    items: ["spirit_vessel", "skadi", "eye_of_skadi", "nullifier"],
    reason: "vs healing",
  },
  {
    tags: ["passive"],
    items: ["silver_edge"],
    reason: "Break vs stacked passives",
  },
  {
    tags: ["stun"],
    items: ["cyclone", "wind_waker", "force_staff", "glimmer_cape", "black_king_bar"],
    reason: "save or ignore stuns",
  },
];

export function tagsForShortName(shortName: string): HeroTag[] {
  return HERO_TAGS[shortName] ?? [];
}
